openapi: 3.0.3
info:
  title: Op-Stack Executor - Hierarchy API (Agent ID Extension)
  version: 1.1.0
  description: |
    Hierarchy API 扩展，支持 agent_id 字段。

    主要变更：
    - 新增 `global_supervisor_agent` 对象结构
    - 新增 `team_supervisor_agent` 对象结构
    - Worker 新增 `agent_id` 字段
    - 向后兼容旧版请求格式

servers:
  - url: http://localhost:8082
    description: Development server

paths:
  /api/executor/v1/hierarchies/create:
    post:
      summary: 创建层级团队
      description: |
        创建新的层级团队配置。支持两种请求格式：
        1. 新格式：使用 `global_supervisor_agent` 和 `team_supervisor_agent`
        2. 旧格式：使用 `global_prompt` 和 `supervisor_prompt`（向后兼容）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HierarchyCreateRequest'
            examples:
              new_format:
                summary: 新格式（推荐）
                value:
                  name: "研究团队"
                  description: "AI研究团队"
                  global_supervisor_agent:
                    agent_id: "gs-research-001"
                    prompt: "你是首席科学家..."
                    temperature: 0.7
                    max_tokens: 2048
                  execution_mode: "sequential"
                  enable_context_sharing: true
                  teams:
                    - name: "理论研究组"
                      team_supervisor_agent:
                        agent_id: "ts-theory-001"
                        prompt: "你是理论研究组负责人..."
                      workers:
                        - agent_id: "w-theory-expert-001"
                          name: "理论专家"
                          role: "理论研究员"
                          system_prompt: "你是理论专家..."
              old_format:
                summary: 旧格式（向后兼容）
                value:
                  name: "研究团队"
                  global_prompt: "你是首席科学家..."
                  teams:
                    - name: "理论研究组"
                      supervisor_prompt: "你是理论研究组负责人..."
                      workers:
                        - name: "理论专家"
                          role: "理论研究员"
                          system_prompt: "你是理论专家..."
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HierarchyResponse'
        '400':
          description: 请求参数错误或 agent_id 冲突
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                duplicate_agent_id:
                  summary: agent_id 重复
                  value:
                    success: false
                    error: "agent_id 'gs-research-001' already exists"
                    code: 400001

  /api/executor/v1/hierarchies/get:
    post:
      summary: 获取层级团队详情
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  description: 层级团队 ID
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HierarchyResponse'

components:
  schemas:
    # Agent 配置对象
    AgentConfig:
      type: object
      properties:
        agent_id:
          type: string
          maxLength: 100
          description: |
            Agent 唯一标识。在同一 Hierarchy Team 内唯一。
            不同 Hierarchy 之间可以使用相同的 agent_id。
            未传入时系统自动生成 UUID。
        prompt:
          type: string
          description: Agent 提示词
        model_id:
          type: string
          description: 使用的 AI 模型 ID（可选）
        temperature:
          type: number
          default: 0.7
          minimum: 0
          maximum: 1
        max_tokens:
          type: integer
          default: 2048
        top_p:
          type: number
          default: 0.9

    # Worker 配置
    WorkerConfig:
      type: object
      required:
        - name
        - role
        - system_prompt
      properties:
        agent_id:
          type: string
          maxLength: 100
          description: Worker 的 agent_id，在同一 Hierarchy 内唯一
        name:
          type: string
          maxLength: 100
        role:
          type: string
          maxLength: 200
        system_prompt:
          type: string
        tools:
          type: array
          items:
            type: string
          default: []
        temperature:
          type: number
          default: 0.7
        max_tokens:
          type: integer
          default: 2048

    # Team 配置
    TeamConfig:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 100
        team_supervisor_agent:
          $ref: '#/components/schemas/AgentConfig'
          description: Team Supervisor Agent 配置（新格式）
        supervisor_prompt:
          type: string
          description: Team Supervisor 提示词（旧格式，向后兼容）
        prevent_duplicate:
          type: boolean
          default: true
        share_context:
          type: boolean
          default: false
        workers:
          type: array
          items:
            $ref: '#/components/schemas/WorkerConfig'

    # Hierarchy 创建请求
    HierarchyCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 100
          description: 层级团队名称
        description:
          type: string
          description: 描述（可选）
        global_supervisor_agent:
          $ref: '#/components/schemas/AgentConfig'
          description: Global Supervisor Agent 配置（新格式）
        global_prompt:
          type: string
          description: Global Supervisor 提示词（旧格式，向后兼容）
        execution_mode:
          type: string
          enum: [sequential, parallel]
          default: sequential
        enable_context_sharing:
          type: boolean
          default: false
        teams:
          type: array
          items:
            $ref: '#/components/schemas/TeamConfig'

    # Hierarchy 响应
    HierarchyResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            global_supervisor_agent:
              type: object
              properties:
                agent_id:
                  type: string
                prompt:
                  type: string
            teams:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  team_supervisor_agent:
                    type: object
                    properties:
                      agent_id:
                        type: string
                      prompt:
                        type: string
                  workers:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        agent_id:
                          type: string
                        name:
                          type: string
                        role:
                          type: string

    # 错误响应
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        code:
          type: integer

    # Stream Event (简化后)
    StreamEvent:
      type: object
      description: LLM 相关事件的简化结构
      properties:
        event:
          type: string
          enum: [llm_stream, llm_reasoning, llm_tool_call]
          description: |
            事件类型：
            - llm_stream: LLM 实时输出片段
            - llm_reasoning: LLM 推理过程
            - llm_tool_call: LLM 工具调用
        data:
          type: object
          required:
            - agent_id
            - timestamp
            - run_id
          properties:
            content:
              type: string
              description: LLM 输出内容
            agent_id:
              type: string
              description: 输出来源 Agent 的 ID（在 Hierarchy 内唯一）
            timestamp:
              type: string
              format: date-time
              description: 精确到毫秒的时间戳 (ISO 8601)
              example: "2025-12-30T10:30:00.123Z"
            run_id:
              type: string
              description: 执行运行 ID
            tool_name:
              type: string
              description: 工具名称（仅 llm_tool_call 事件）
            tool_count:
              type: integer
              description: 工具调用计数（仅 llm_tool_call 事件）
